# =====================================================================
# AI Coding Agent Platform — dev convenience targets
# =====================================================================
.DEFAULT_GOAL := help

SHELL := /bin/bash
COMPOSE := docker compose

# ---------- top-level ----------
.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\nTargets:\n"} \
	/^[a-zA-Z0-9_.-]+:.*?##/ { printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2 } \
	/^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Stack
.PHONY: dev up down logs ps restart clean
dev: ## Build & start full dev stack (postgres, redis, qdrant, api, web, nginx)
	$(COMPOSE) up --build

up: ## Start stack in background
	$(COMPOSE) up -d

down: ## Stop stack
	$(COMPOSE) down

logs: ## Tail all logs
	$(COMPOSE) logs -f --tail=200

ps: ## Show running services
	$(COMPOSE) ps

restart: ## Restart api + web only
	$(COMPOSE) restart api web

clean: ## Stop and remove volumes (DESTROYS DATA)
	$(COMPOSE) down -v

##@ API
.PHONY: api-sh api-test api-fmt api-lint api-type api-mig api-upgrade api-downgrade api-shell-py
api-sh: ## Shell into the api container
	$(COMPOSE) exec api sh

api-test: ## Run backend tests
	$(COMPOSE) exec api pytest -q

api-fmt: ## Ruff format + fix
	$(COMPOSE) exec api ruff format .
	$(COMPOSE) exec api ruff check --fix .

api-lint: ## Ruff check (no fix)
	$(COMPOSE) exec api ruff check .

api-type: ## Mypy type-check
	$(COMPOSE) exec api mypy app

api-mig: ## Create autogenerated migration; usage: make api-mig msg="add users"
	$(COMPOSE) exec api alembic revision --autogenerate -m "$(msg)"

api-upgrade: ## Apply migrations up to head
	$(COMPOSE) exec api alembic upgrade head

api-downgrade: ## Roll back one migration
	$(COMPOSE) exec api alembic downgrade -1

api-shell-py: ## IPython shell inside the api container
	$(COMPOSE) exec api python -m IPython

##@ Web
.PHONY: web-sh web-dev web-build web-lint web-test
web-sh: ## Shell into the web container
	$(COMPOSE) exec web sh

web-dev: ## Run vite dev server outside docker (host node required)
	cd apps/web && pnpm install && pnpm dev

web-build: ## Production build of frontend
	cd apps/web && pnpm install && pnpm build

web-lint: ## ESLint
	cd apps/web && pnpm lint

web-test: ## Vitest
	cd apps/web && pnpm test
