{{- if .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "aca.fullname" . }}-api
  labels:
    {{- include "aca.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "aca.selectorLabels" (dict "ctx" . "component" "api") | nindent 6 }}
{{- end }}
