{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aca.fullname" . }}-redis
  labels:
    {{- include "aca.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
  selector:
    {{- include "aca.selectorLabels" (dict "ctx" . "component" "redis") | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aca.fullname" . }}-redis
  labels:
    {{- include "aca.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "aca.selectorLabels" (dict "ctx" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aca.selectorLabels" (dict "ctx" . "component" "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args: ["redis-server", "--appendonly", "yes"]
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
{{- end }}
