"""GitHub orchestration (Phase 6).

- create_pr: branch off `base`, commit the given file changes, open a PR.
- review_pr: fetch the PR diff, have the LLM review it, optionally post the
  review as a PR comment.

Reuses the Phase 4 LLM provider abstraction so reviews run on whatever model
the platform is configured for (Ollama / OpenAI).
"""
from __future__ import annotations

from app.core.config import settings
from app.core.logging import get_logger
from app.domain.github.schemas import (
    CreatePRRequest,
    CreatePRResponse,
    ReviewPRRequest,
    ReviewPRResponse,
)
from app.infrastructure.github.client import GitHubClient, GitHubError
from app.infrastructure.llm import ChatMessage, get_llm_provider

log = get_logger("github")

# Cap the diff we feed the model so a huge PR doesn't blow the context window.
_MAX_DIFF_CHARS = 24_000

_REVIEW_SYSTEM_PROMPT = """\
You are a senior code reviewer. Review the following pull request diff and give
concise, actionable feedback. Focus on: correctness bugs, security issues,
error handling, and clarity. Use short bullet points grouped by file. If the
diff looks good, say so briefly. Do NOT invent code that isn't in the diff.
"""


class GitHubService:
    def __init__(self) -> None:
        self.client = GitHubClient()

    async def status(self) -> tuple[bool, str | None, str | None]:
        if not self.client.configured:
            return False, None, None
        try:
            me = await self.client.whoami()
            return True, me.get("login"), me.get("name")
        except GitHubError:
            return True, None, None

    async def create_pr(self, req: CreatePRRequest) -> CreatePRResponse:
        # 1. branch off base
        base_sha = await self.client.get_branch_sha(req.owner, req.repo, req.base)
        try:
            await self.client.create_branch(req.owner, req.repo, req.branch, base_sha)
        except GitHubError as e:
            # 422 = ref already exists; reuse it (lets you push more commits)
            if e.status != 422:
                raise

        # 2. commit each file change to the branch
        for ch in req.changes:
            await self.client.put_file(
                req.owner,
                req.repo,
                path=ch.path,
                content=ch.content,
                message=f"{req.title}: update {ch.path}",
                branch=req.branch,
            )

        # 3. open the PR
        pr = await self.client.create_pull(
            req.owner,
            req.repo,
            title=req.title,
            head=req.branch,
            base=req.base,
            body=req.body,
            draft=req.draft,
        )
        return CreatePRResponse(
            number=pr["number"], url=pr["html_url"], branch=req.branch
        )

    async def review_pr(self, req: ReviewPRRequest) -> ReviewPRResponse:
        diff = await self.client.get_pull_diff(req.owner, req.repo, req.number)
        truncated = len(diff) > _MAX_DIFF_CHARS
        if truncated:
            diff = diff[:_MAX_DIFF_CHARS] + "\n... [diff truncated] ..."

        provider = get_llm_provider()
        messages = [
            ChatMessage(role="system", content=_REVIEW_SYSTEM_PROMPT),
            ChatMessage(
                role="user",
                content=f"Review this pull request diff:\n\n```diff\n{diff}\n```",
            ),
        ]
        resp = await provider.chat(messages, temperature=0.2, max_tokens=1024)
        review = resp.content.strip() or "(model returned no review text)"

        comment_url: str | None = None
        if req.post_comment:
            body = (
                f"### 🤖 AI code review\n\n{review}\n\n"
                f"<sub>Generated by AI Coding Agent using "
                f"{provider.name}/{provider.model}.</sub>"
            )
            posted = await self.client.comment_on_issue(
                req.owner, req.repo, req.number, body
            )
            comment_url = posted.get("html_url")

        return ReviewPRResponse(
            review=review, comment_url=comment_url, diff_truncated=truncated
        )
